/*
Keycloak Admin REST API

Testing WorkflowsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_WorkflowsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WorkflowsAPIService AdminRealmsRealmWorkflowsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var realm string

		resp, httpRes, err := apiClient.WorkflowsAPI.AdminRealmsRealmWorkflowsGet(context.Background(), realm).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkflowsAPIService AdminRealmsRealmWorkflowsIdActivateTypeResourceIdPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var realm string
		var id string
		var resourceId string
		var type_ openapiclient.map[string]interface{}

		httpRes, err := apiClient.WorkflowsAPI.AdminRealmsRealmWorkflowsIdActivateTypeResourceIdPost(context.Background(), realm, id, resourceId, type_).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkflowsAPIService AdminRealmsRealmWorkflowsIdDeactivateTypeResourceIdPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var realm string
		var id string
		var resourceId string
		var type_ openapiclient.map[string]interface{}

		httpRes, err := apiClient.WorkflowsAPI.AdminRealmsRealmWorkflowsIdDeactivateTypeResourceIdPost(context.Background(), realm, id, resourceId, type_).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkflowsAPIService AdminRealmsRealmWorkflowsIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var realm string
		var id string

		httpRes, err := apiClient.WorkflowsAPI.AdminRealmsRealmWorkflowsIdDelete(context.Background(), realm, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkflowsAPIService AdminRealmsRealmWorkflowsIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var realm string
		var id string

		resp, httpRes, err := apiClient.WorkflowsAPI.AdminRealmsRealmWorkflowsIdGet(context.Background(), realm, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkflowsAPIService AdminRealmsRealmWorkflowsIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var realm string
		var id string

		httpRes, err := apiClient.WorkflowsAPI.AdminRealmsRealmWorkflowsIdPut(context.Background(), realm, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkflowsAPIService AdminRealmsRealmWorkflowsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var realm string

		httpRes, err := apiClient.WorkflowsAPI.AdminRealmsRealmWorkflowsPost(context.Background(), realm).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkflowsAPIService AdminRealmsRealmWorkflowsScheduledResourceIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var realm string
		var resourceId string

		resp, httpRes, err := apiClient.WorkflowsAPI.AdminRealmsRealmWorkflowsScheduledResourceIdGet(context.Background(), realm, resourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
