/*
Keycloak Admin REST API

This is a REST API reference for the Keycloak Admin REST API.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OrganizationInvitationRepresentation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationInvitationRepresentation{}

// OrganizationInvitationRepresentation struct for OrganizationInvitationRepresentation
type OrganizationInvitationRepresentation struct {
	Id *string `json:"id,omitempty"`
	OrganizationId *string `json:"organizationId,omitempty"`
	Email *string `json:"email,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName *string `json:"lastName,omitempty"`
	SentDate *int32 `json:"sentDate,omitempty"`
	ExpiresAt *int32 `json:"expiresAt,omitempty"`
	Status *Status `json:"status,omitempty"`
	InviteLink *string `json:"inviteLink,omitempty"`
}

// NewOrganizationInvitationRepresentation instantiates a new OrganizationInvitationRepresentation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationInvitationRepresentation() *OrganizationInvitationRepresentation {
	this := OrganizationInvitationRepresentation{}
	return &this
}

// NewOrganizationInvitationRepresentationWithDefaults instantiates a new OrganizationInvitationRepresentation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationInvitationRepresentationWithDefaults() *OrganizationInvitationRepresentation {
	this := OrganizationInvitationRepresentation{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrganizationInvitationRepresentation) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationInvitationRepresentation) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrganizationInvitationRepresentation) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OrganizationInvitationRepresentation) SetId(v string) {
	o.Id = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *OrganizationInvitationRepresentation) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationInvitationRepresentation) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *OrganizationInvitationRepresentation) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *OrganizationInvitationRepresentation) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *OrganizationInvitationRepresentation) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationInvitationRepresentation) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *OrganizationInvitationRepresentation) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *OrganizationInvitationRepresentation) SetEmail(v string) {
	o.Email = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *OrganizationInvitationRepresentation) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationInvitationRepresentation) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *OrganizationInvitationRepresentation) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *OrganizationInvitationRepresentation) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *OrganizationInvitationRepresentation) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationInvitationRepresentation) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *OrganizationInvitationRepresentation) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *OrganizationInvitationRepresentation) SetLastName(v string) {
	o.LastName = &v
}

// GetSentDate returns the SentDate field value if set, zero value otherwise.
func (o *OrganizationInvitationRepresentation) GetSentDate() int32 {
	if o == nil || IsNil(o.SentDate) {
		var ret int32
		return ret
	}
	return *o.SentDate
}

// GetSentDateOk returns a tuple with the SentDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationInvitationRepresentation) GetSentDateOk() (*int32, bool) {
	if o == nil || IsNil(o.SentDate) {
		return nil, false
	}
	return o.SentDate, true
}

// HasSentDate returns a boolean if a field has been set.
func (o *OrganizationInvitationRepresentation) HasSentDate() bool {
	if o != nil && !IsNil(o.SentDate) {
		return true
	}

	return false
}

// SetSentDate gets a reference to the given int32 and assigns it to the SentDate field.
func (o *OrganizationInvitationRepresentation) SetSentDate(v int32) {
	o.SentDate = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *OrganizationInvitationRepresentation) GetExpiresAt() int32 {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret int32
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationInvitationRepresentation) GetExpiresAtOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *OrganizationInvitationRepresentation) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given int32 and assigns it to the ExpiresAt field.
func (o *OrganizationInvitationRepresentation) SetExpiresAt(v int32) {
	o.ExpiresAt = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OrganizationInvitationRepresentation) GetStatus() Status {
	if o == nil || IsNil(o.Status) {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationInvitationRepresentation) GetStatusOk() (*Status, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OrganizationInvitationRepresentation) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *OrganizationInvitationRepresentation) SetStatus(v Status) {
	o.Status = &v
}

// GetInviteLink returns the InviteLink field value if set, zero value otherwise.
func (o *OrganizationInvitationRepresentation) GetInviteLink() string {
	if o == nil || IsNil(o.InviteLink) {
		var ret string
		return ret
	}
	return *o.InviteLink
}

// GetInviteLinkOk returns a tuple with the InviteLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationInvitationRepresentation) GetInviteLinkOk() (*string, bool) {
	if o == nil || IsNil(o.InviteLink) {
		return nil, false
	}
	return o.InviteLink, true
}

// HasInviteLink returns a boolean if a field has been set.
func (o *OrganizationInvitationRepresentation) HasInviteLink() bool {
	if o != nil && !IsNil(o.InviteLink) {
		return true
	}

	return false
}

// SetInviteLink gets a reference to the given string and assigns it to the InviteLink field.
func (o *OrganizationInvitationRepresentation) SetInviteLink(v string) {
	o.InviteLink = &v
}

func (o OrganizationInvitationRepresentation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationInvitationRepresentation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.SentDate) {
		toSerialize["sentDate"] = o.SentDate
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.InviteLink) {
		toSerialize["inviteLink"] = o.InviteLink
	}
	return toSerialize, nil
}

type NullableOrganizationInvitationRepresentation struct {
	value *OrganizationInvitationRepresentation
	isSet bool
}

func (v NullableOrganizationInvitationRepresentation) Get() *OrganizationInvitationRepresentation {
	return v.value
}

func (v *NullableOrganizationInvitationRepresentation) Set(val *OrganizationInvitationRepresentation) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationInvitationRepresentation) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationInvitationRepresentation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationInvitationRepresentation(val *OrganizationInvitationRepresentation) *NullableOrganizationInvitationRepresentation {
	return &NullableOrganizationInvitationRepresentation{value: val, isSet: true}
}

func (v NullableOrganizationInvitationRepresentation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationInvitationRepresentation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


