/*
Keycloak Admin REST API

This is a REST API reference for the Keycloak Admin REST API.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkflowStepRepresentation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowStepRepresentation{}

// WorkflowStepRepresentation struct for WorkflowStepRepresentation
type WorkflowStepRepresentation struct {
	Uses *string `json:"uses,omitempty"`
	After *string `json:"after,omitempty"`
	ScheduledAt *int64 `json:"scheduled-at,omitempty"`
	Id *string `json:"id,omitempty"`
	Config *map[string][]string `json:"config,omitempty"`
}

// NewWorkflowStepRepresentation instantiates a new WorkflowStepRepresentation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowStepRepresentation() *WorkflowStepRepresentation {
	this := WorkflowStepRepresentation{}
	return &this
}

// NewWorkflowStepRepresentationWithDefaults instantiates a new WorkflowStepRepresentation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowStepRepresentationWithDefaults() *WorkflowStepRepresentation {
	this := WorkflowStepRepresentation{}
	return &this
}

// GetUses returns the Uses field value if set, zero value otherwise.
func (o *WorkflowStepRepresentation) GetUses() string {
	if o == nil || IsNil(o.Uses) {
		var ret string
		return ret
	}
	return *o.Uses
}

// GetUsesOk returns a tuple with the Uses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStepRepresentation) GetUsesOk() (*string, bool) {
	if o == nil || IsNil(o.Uses) {
		return nil, false
	}
	return o.Uses, true
}

// HasUses returns a boolean if a field has been set.
func (o *WorkflowStepRepresentation) HasUses() bool {
	if o != nil && !IsNil(o.Uses) {
		return true
	}

	return false
}

// SetUses gets a reference to the given string and assigns it to the Uses field.
func (o *WorkflowStepRepresentation) SetUses(v string) {
	o.Uses = &v
}

// GetAfter returns the After field value if set, zero value otherwise.
func (o *WorkflowStepRepresentation) GetAfter() string {
	if o == nil || IsNil(o.After) {
		var ret string
		return ret
	}
	return *o.After
}

// GetAfterOk returns a tuple with the After field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStepRepresentation) GetAfterOk() (*string, bool) {
	if o == nil || IsNil(o.After) {
		return nil, false
	}
	return o.After, true
}

// HasAfter returns a boolean if a field has been set.
func (o *WorkflowStepRepresentation) HasAfter() bool {
	if o != nil && !IsNil(o.After) {
		return true
	}

	return false
}

// SetAfter gets a reference to the given string and assigns it to the After field.
func (o *WorkflowStepRepresentation) SetAfter(v string) {
	o.After = &v
}

// GetScheduledAt returns the ScheduledAt field value if set, zero value otherwise.
func (o *WorkflowStepRepresentation) GetScheduledAt() int64 {
	if o == nil || IsNil(o.ScheduledAt) {
		var ret int64
		return ret
	}
	return *o.ScheduledAt
}

// GetScheduledAtOk returns a tuple with the ScheduledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStepRepresentation) GetScheduledAtOk() (*int64, bool) {
	if o == nil || IsNil(o.ScheduledAt) {
		return nil, false
	}
	return o.ScheduledAt, true
}

// HasScheduledAt returns a boolean if a field has been set.
func (o *WorkflowStepRepresentation) HasScheduledAt() bool {
	if o != nil && !IsNil(o.ScheduledAt) {
		return true
	}

	return false
}

// SetScheduledAt gets a reference to the given int64 and assigns it to the ScheduledAt field.
func (o *WorkflowStepRepresentation) SetScheduledAt(v int64) {
	o.ScheduledAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WorkflowStepRepresentation) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStepRepresentation) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WorkflowStepRepresentation) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WorkflowStepRepresentation) SetId(v string) {
	o.Id = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *WorkflowStepRepresentation) GetConfig() map[string][]string {
	if o == nil || IsNil(o.Config) {
		var ret map[string][]string
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStepRepresentation) GetConfigOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *WorkflowStepRepresentation) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string][]string and assigns it to the Config field.
func (o *WorkflowStepRepresentation) SetConfig(v map[string][]string) {
	o.Config = &v
}

func (o WorkflowStepRepresentation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowStepRepresentation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uses) {
		toSerialize["uses"] = o.Uses
	}
	if !IsNil(o.After) {
		toSerialize["after"] = o.After
	}
	if !IsNil(o.ScheduledAt) {
		toSerialize["scheduled-at"] = o.ScheduledAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableWorkflowStepRepresentation struct {
	value *WorkflowStepRepresentation
	isSet bool
}

func (v NullableWorkflowStepRepresentation) Get() *WorkflowStepRepresentation {
	return v.value
}

func (v *NullableWorkflowStepRepresentation) Set(val *WorkflowStepRepresentation) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowStepRepresentation) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowStepRepresentation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowStepRepresentation(val *WorkflowStepRepresentation) *NullableWorkflowStepRepresentation {
	return &NullableWorkflowStepRepresentation{value: val, isSet: true}
}

func (v NullableWorkflowStepRepresentation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowStepRepresentation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


