/*
Keycloak Admin REST API

This is a REST API reference for the Keycloak Admin REST API.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkflowConcurrencyRepresentation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowConcurrencyRepresentation{}

// WorkflowConcurrencyRepresentation struct for WorkflowConcurrencyRepresentation
type WorkflowConcurrencyRepresentation struct {
	CancelInProgress *string `json:"cancel-in-progress,omitempty"`
	RestartInProgress *string `json:"restart-in-progress,omitempty"`
}

// NewWorkflowConcurrencyRepresentation instantiates a new WorkflowConcurrencyRepresentation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowConcurrencyRepresentation() *WorkflowConcurrencyRepresentation {
	this := WorkflowConcurrencyRepresentation{}
	return &this
}

// NewWorkflowConcurrencyRepresentationWithDefaults instantiates a new WorkflowConcurrencyRepresentation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowConcurrencyRepresentationWithDefaults() *WorkflowConcurrencyRepresentation {
	this := WorkflowConcurrencyRepresentation{}
	return &this
}

// GetCancelInProgress returns the CancelInProgress field value if set, zero value otherwise.
func (o *WorkflowConcurrencyRepresentation) GetCancelInProgress() string {
	if o == nil || IsNil(o.CancelInProgress) {
		var ret string
		return ret
	}
	return *o.CancelInProgress
}

// GetCancelInProgressOk returns a tuple with the CancelInProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowConcurrencyRepresentation) GetCancelInProgressOk() (*string, bool) {
	if o == nil || IsNil(o.CancelInProgress) {
		return nil, false
	}
	return o.CancelInProgress, true
}

// HasCancelInProgress returns a boolean if a field has been set.
func (o *WorkflowConcurrencyRepresentation) HasCancelInProgress() bool {
	if o != nil && !IsNil(o.CancelInProgress) {
		return true
	}

	return false
}

// SetCancelInProgress gets a reference to the given string and assigns it to the CancelInProgress field.
func (o *WorkflowConcurrencyRepresentation) SetCancelInProgress(v string) {
	o.CancelInProgress = &v
}

// GetRestartInProgress returns the RestartInProgress field value if set, zero value otherwise.
func (o *WorkflowConcurrencyRepresentation) GetRestartInProgress() string {
	if o == nil || IsNil(o.RestartInProgress) {
		var ret string
		return ret
	}
	return *o.RestartInProgress
}

// GetRestartInProgressOk returns a tuple with the RestartInProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowConcurrencyRepresentation) GetRestartInProgressOk() (*string, bool) {
	if o == nil || IsNil(o.RestartInProgress) {
		return nil, false
	}
	return o.RestartInProgress, true
}

// HasRestartInProgress returns a boolean if a field has been set.
func (o *WorkflowConcurrencyRepresentation) HasRestartInProgress() bool {
	if o != nil && !IsNil(o.RestartInProgress) {
		return true
	}

	return false
}

// SetRestartInProgress gets a reference to the given string and assigns it to the RestartInProgress field.
func (o *WorkflowConcurrencyRepresentation) SetRestartInProgress(v string) {
	o.RestartInProgress = &v
}

func (o WorkflowConcurrencyRepresentation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowConcurrencyRepresentation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CancelInProgress) {
		toSerialize["cancel-in-progress"] = o.CancelInProgress
	}
	if !IsNil(o.RestartInProgress) {
		toSerialize["restart-in-progress"] = o.RestartInProgress
	}
	return toSerialize, nil
}

type NullableWorkflowConcurrencyRepresentation struct {
	value *WorkflowConcurrencyRepresentation
	isSet bool
}

func (v NullableWorkflowConcurrencyRepresentation) Get() *WorkflowConcurrencyRepresentation {
	return v.value
}

func (v *NullableWorkflowConcurrencyRepresentation) Set(val *WorkflowConcurrencyRepresentation) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowConcurrencyRepresentation) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowConcurrencyRepresentation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowConcurrencyRepresentation(val *WorkflowConcurrencyRepresentation) *NullableWorkflowConcurrencyRepresentation {
	return &NullableWorkflowConcurrencyRepresentation{value: val, isSet: true}
}

func (v NullableWorkflowConcurrencyRepresentation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowConcurrencyRepresentation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


