/*
Keycloak Admin REST API

This is a REST API reference for the Keycloak Admin REST API.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ErrorRepresentation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorRepresentation{}

// ErrorRepresentation struct for ErrorRepresentation
type ErrorRepresentation struct {
	Field *string `json:"field,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Params []interface{} `json:"params,omitempty"`
	Errors []ErrorRepresentation `json:"errors,omitempty"`
}

// NewErrorRepresentation instantiates a new ErrorRepresentation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorRepresentation() *ErrorRepresentation {
	this := ErrorRepresentation{}
	return &this
}

// NewErrorRepresentationWithDefaults instantiates a new ErrorRepresentation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorRepresentationWithDefaults() *ErrorRepresentation {
	this := ErrorRepresentation{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *ErrorRepresentation) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorRepresentation) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *ErrorRepresentation) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *ErrorRepresentation) SetField(v string) {
	o.Field = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ErrorRepresentation) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorRepresentation) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ErrorRepresentation) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *ErrorRepresentation) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *ErrorRepresentation) GetParams() []interface{} {
	if o == nil || IsNil(o.Params) {
		var ret []interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorRepresentation) GetParamsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *ErrorRepresentation) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given []interface{} and assigns it to the Params field.
func (o *ErrorRepresentation) SetParams(v []interface{}) {
	o.Params = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ErrorRepresentation) GetErrors() []ErrorRepresentation {
	if o == nil || IsNil(o.Errors) {
		var ret []ErrorRepresentation
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorRepresentation) GetErrorsOk() ([]ErrorRepresentation, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ErrorRepresentation) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ErrorRepresentation and assigns it to the Errors field.
func (o *ErrorRepresentation) SetErrors(v []ErrorRepresentation) {
	o.Errors = v
}

func (o ErrorRepresentation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorRepresentation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableErrorRepresentation struct {
	value *ErrorRepresentation
	isSet bool
}

func (v NullableErrorRepresentation) Get() *ErrorRepresentation {
	return v.value
}

func (v *NullableErrorRepresentation) Set(val *ErrorRepresentation) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorRepresentation) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorRepresentation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorRepresentation(val *ErrorRepresentation) *NullableErrorRepresentation {
	return &NullableErrorRepresentation{value: val, isSet: true}
}

func (v NullableErrorRepresentation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorRepresentation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


